### ISSUE TITLE
Using optout branch with bower --force-latest.

### ISSUE THREAD

**Issue by hastebrot** [vaadin/vaadin-usage-statistics#18]
It seems Bower with `--force-latest` has problems to use the `optout` branch, even when we define the commit hash in `resolutions`.

Excerpt from `bower.json`:

~~~json
{
  "dependencies": {
    "vaadin-grid": "vaadin/vaadin-grid#5.0.4",
    "vaadin-usage-statistics": "vaadin/vaadin-usage-statistics#optout"
  },
  "resolutions": {
    "vaadin-usage-statistics": "e-tag:61ea340"
  }
}
~~~

**Comment by hastebrot** [comment]
Ok, instead of the commit the branch needs to be specified:

~~~json
  "resolutions": {
    "vaadin-usage-statistics": "optout"
  }
~~~

**Comment by web-padawan** [comment]
Yes, the branch name is the correct way of using resolutions. Sorry for late response, closing as resolved.
