### ISSUE TITLE
Remove list of Vaadin elements

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-usage-statistics#25]
There is no way that this can work if you list Vaadin elements to check for. The list is already outdated / missing elements.

**Comment by web-padawan** [comment]
Currently, for Polymer 3 the global `Vaadin` namespace does not contain references to the components classes.

One possible solution:
1. Use `vaadin-element-mixin` for following components:
- Lumo: https://github.com/vaadin/vaadin-lumo-styles/blob/f8a592226bf0fe7faf6ab20868d24c755fb48b6d/version.html#L8
- Material: https://github.com/vaadin/vaadin-material-styles/blob/3fcc14857ca75f6c898968f28bfac86ee627fa0f/version.html#L8
- Router: https://github.com/vaadin/vaadin-router/blob/82e6262becfb24a147ead5f2b89c31350130e437/src/router-meta.js#L6
2. Update the `ElementMixin` to use `static finalize()` and add the `static get is()` getter value back to `Vaadin` namespace, e. g. to `Vaadin.registrations` similarly to how Polymer does that: https://github.com/Polymer/polymer/blob/0bf1e60c157b9ecdf56b6e308aeaea16d34ee04b/lib/mixins/element-mixin.js#L694
