### ISSUE TITLE
options in package.json

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-usage-statistics#35]
It would be nice to have an option in the package.json file to avoid using the vaadin-stats module instead of running a command. 

Exemple:  **package.json**
```
{
  ...
  anonymousStatistics: false     // or vaadinStats: false
  ...
}
```

**Comment by yveslange** [comment]
Also, it seems that bash should be present to be able to execute this command. I really think that it's a bad move (specially for people not running the WSL. Therefore not having bash).

**Comment by Artur-** [comment]
Hi, in what case is "bash" needed to opt out? Tried running the opt out on Windows and there was no mention of bash anywhere.

I created a PR for allow disabling stats per project in addition to per machine: #36

**Comment by yveslange** [comment]
We were running the command in a linux docker container that does not have bash. We got an error saying that bash was not found. 

I badly assumed that it would have been the same on windows :)
