### ISSUE TITLE
Missing script disable in 2.1.1

### ISSUE THREAD

**Issue by ungear** [vaadin/vaadin-usage-statistics#52]
In npm package version 2.1.1 there is no **disable** script in **package.json**. As a result, opting out via command `npm explore @vaadin/vaadin-usage-statistics -- npm run disable` fails with error `missing script: disable`

**Comment by web-padawan** [comment]
Thanks for the issue. It's caused by incorrect update of our Polymer 3 conversion utility. I will work on a fix.

**Comment by web-padawan** [comment]
Fix is released in `v2.1.2`.
